name: Prédiction quotidienne -> Google Drive

on:
  schedule:
    - cron: '0 5 * * *'  # Tous les jours à 6h heure Maroc (UTC+1)
  workflow_dispatch:

jobs:
  run_prediction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installer dépendances
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client openpyxl

      - name: Exécuter le script de prédiction
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: python prediction.py
